version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "javaLambda"
        Alias: "SBLambdaFnAlias"
        CurrentVersion: 1
        TargetVersion: 1